### ISSUE TITLE
How to access state without request?

### ISSUE THREAD

**Issue by pySilver** [illagrenan/django-asgi-lifespan#105]
I'm wondering what would be the correct way to access state from functions that are not having access to request? Let's say we have a function `async def ping_some_url()...` which is called from `instance.asave()` which may be called within a view or management command. 

How do I avoid passing `client session` everywhere? I was thinking about keeping reference to a session in app config but haven't found good design for that yet. What are your thoughts @illagrenan ? Maybe I should use some wrapping function around `aiohttp.ClientSession()` so it will also set a reference to app config variable? Making session available for the project everywhere? This will probably work, but `shutdown` will not be available outside of asgi context.

**Comment by pySilver** [comment]
Actually that will not work that way because`ready` is not an async method. We need to define a function like `async def get_client_session()` that may access global request and lookup for session there or initialize it's own copy if not found.

**Comment by pySilver** [comment]
An example:

```python
# aiohttp.py
import asyncio

import aiohttp


class LazyClientSession:
    _instance = None
    _lock = asyncio.Lock()

    @classmethod
    async def get_instance(cls) -> aiohttp.ClientSession:
        async with cls._lock:
            if cls._instance is None or cls._instance.closed:
                cls._instance = aiohttp.ClientSession()
            return cls._instance


async def get_client_session() -> aiohttp.ClientSession:
    return await LazyClientSession.get_instance()
```

and context:

```python
from contextlib import asynccontextmanager

from django_asgi_lifespan.types import LifespanManager

from mybaze.core.aiohttp import get_client_session


@asynccontextmanager
async def lifespan_manager() -> LifespanManager:
    state = {
        "aiohttp_client": await get_client_session(),
    }

    try:
        yield state
    finally:
        await state["aiohttp_client"].close()
```

**Comment by illagrenan** [comment]
Hi, thanks for the great question, and sorry for the delay in replying. Unfortunately, I can't think of anything particularly elegant and clean. I see two major obstacles there:

1. We need somewhere to hold the global state. This leads to some global variable or singleton, and I think that's not a clean solution.
2. Uvicorn (or other ASGI servers) create the event loop for us. In Django, we don't have any eventloop outside the request-response loop; we have to create it ourselves. Therefore, we can't use, e.g., Django settings to store the global state.

There is always some global state there, but in the case of the Lifespan protocol, [the ASGI server holds the global state](https://asgi.readthedocs.io/en/latest/specs/lifespan.html#lifespan-state), so it looks clean.

In [this PR](https://github.com/illagrenan/django-asgi-lifespan/pull/108), I have prepared a sample [Django management command](https://github.com/illagrenan/django-asgi-lifespan/blob/feature/105-no-request/tests/django_test_application/test_app/management/commands/use_standalone.py) that:

1. Creates an eventloop.
2. Uses the same context manager that is used in request-response. It stores the output of the manager in a [contextvar](https://docs.python.org/3/library/contextvars.html).
3. The contextvar can then be read as a global state by any function that needs it. Thus, passing this shared resource between all functions or methods that require it is eliminated.
4. Closes the shared resource.

To run the code in the PR:

```bash
$ cd ./tests/django_test_application/
$ poetry run python ./manage.py use_standalone
Installed `<class 'asyncio.windows_events.WindowsSelectorEventLoopPolicy'>` as a loop policy.
Starting command execution
Setting up HTTPX client
Lifespan: Initializing HTTPX client.
Sending HEAD request to https://www.example.com/
HTTP Request: HEAD https://www.example.com/ "HTTP/1.1 200 OK"
Response status code: 200
Cleaning up HTTPX client
Lifespan: Closing HTTPX client.
Command execution completed
```

The advantage of my example is that the same piece of code that is called in the request-response can be used in this way. The disadvantage is everything else: we have a global variable (ContextVar), we have to manage event loops, and we have to close the resource.

I welcome comments and ideas! To be honest, I don't know how to solve this elegantly myself.

**Comment by pySilver** [comment]
Yeah, it's quite complex issue. Do you see any downsides of having lazy loaded global object like in my example? It feels django-ish, at least this is how `cache` and other components are handled (hm, I cannot tell which other components exactly). The obvious downside is that there is no "on shutdown" action. So yeah - if it's something critical, then it may cause some troubles.

**Comment by illagrenan** [comment]
You're right that a similar pattern is commonly used in Django — whether it's `django.core.cache` or `django.db.connection`. I think your global object will work, and it's kind of OK if you somehow handle:

- **synchronization** — that is, that no one tries to access the global object until the object is ready;
- **shutdown action** — although this is probably optional, typically a destructor is called on the object anyway.

To be honest, I miss some service layer / dependency injection in Django, similar to what some PHP frameworks have (e.g.:https://symfony.com/doc/current/service_container.html).

**Comment by pySilver** [comment]
* **Synchronization** - this is  why I use `asyncio.Lock`
* Shutdown - yeah

One can try to use https://lancetnik.github.io/FastDepends/ for DI.

**Comment by pySilver** [comment]
Actually for the management command there is way to reuse lifespan manager:

```python
import asyncio
from collections.abc import Callable
from functools import wraps
from typing import Any, TypeVar

from django.core.management.base import BaseCommand

from config.context import lifespan_manager
from mybaze.feeds.tasks import awesome_task

T = TypeVar("T")


def with_lifespan(func: Callable[..., T]) -> Callable[..., T]:
    @wraps(func)
    def wrapper(*args, **kwargs) -> Any:
        async def run_with_lifespan() -> Any:
            async with lifespan_manager() as state:
                # Inject state into kwargs
                kwargs["state"] = state
                if asyncio.iscoroutinefunction(func):
                    return await func(*args, **kwargs)
                return func(*args, **kwargs)

        return asyncio.get_event_loop().run_until_complete(run_with_lifespan())

    return wrapper


class Command(BaseCommand):
    help = "Run an async task with an asyncio event loop"

    @with_lifespan
    async def handle(  # pyright: ignore [reportIncompatibleMethodOverride]
        self,
        *args,
        state: dict[str, Any] | None = None,
        **options: dict[str, Any],
    ) -> None:
        # Use state here
        print(state)
        await awesome_task.kiq()

```
