### ISSUE TITLE
Why django 5 is not supported?

### ISSUE THREAD

**Issue by dima-kov** [illagrenan/django-asgi-lifespan#82]

**Comment by illagrenan** [comment]
I didn't have time to test this plugin with the new Django 5 yet. However, I think there should be no problem with the integration and everything should work fine. If you run into any problems, please [create a new issue](https://github.com/illagrenan/django-asgi-lifespan/issues/new). I will leave this issue open until I test everything.

**Comment by dima-kov** [comment]
I see, thank you for your input!

I tried with django 5, it has some errors depending on async signals.
